// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/book.proto
// Protobuf Java Version: 4.34.0

package proto;

@com.google.protobuf.Generated
public final class BookProto extends com.google.protobuf.GeneratedFile {
  private BookProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "BookProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string author = 3;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 3;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>int32 price = 4;</code>
     * @return The price.
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code Book}
   */
  public static final class Book extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "Book");
    }
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      title_ = "";
      author_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BookProto.internal_static_Book_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return proto.BookProto.internal_static_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BookProto.internal_static_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BookProto.Book.class, proto.BookProto.Book.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object author_ = "";
    /**
     * <code>string author = 3;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 3;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private int price_ = 0;
    /**
     * <code>int32 price = 4;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, author_);
      }
      if (price_ != 0) {
        output.writeInt32(4, price_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, author_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BookProto.Book)) {
        return super.equals(obj);
      }
      proto.BookProto.Book other = (proto.BookProto.Book) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (getPrice()
          != other.getPrice()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BookProto.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.BookProto.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.BookProto.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.BookProto.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BookProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.BookProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BookProto.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Book)
        proto.BookProto.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BookProto.internal_static_Book_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BookProto.internal_static_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BookProto.Book.class, proto.BookProto.Book.Builder.class);
      }

      // Construct using proto.BookProto.Book.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        title_ = "";
        author_ = "";
        price_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BookProto.internal_static_Book_descriptor;
      }

      @java.lang.Override
      public proto.BookProto.Book getDefaultInstanceForType() {
        return proto.BookProto.Book.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BookProto.Book build() {
        proto.BookProto.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BookProto.Book buildPartial() {
        proto.BookProto.Book result = new proto.BookProto.Book(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.BookProto.Book result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.author_ = author_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.price_ = price_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BookProto.Book) {
          return mergeFrom((proto.BookProto.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BookProto.Book other) {
        if (other == proto.BookProto.Book.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                author_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                price_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 3;</code>
       * @return The author.
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 3;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 3;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        author_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        author_ = getDefaultInstance().getAuthor();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string author = 3;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        author_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>int32 price = 4;</code>
       * @return The price.
       */
      @java.lang.Override
      public int getPrice() {
        return price_;
      }
      /**
       * <code>int32 price = 4;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(int value) {

        price_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Book)
    }

    // @@protoc_insertion_point(class_scope:Book)
    private static final proto.BookProto.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BookProto.Book();
    }

    public static proto.BookProto.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @java.lang.Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BookProto.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Book books = 1;</code>
     */
    java.util.List<proto.BookProto.Book> 
        getBooksList();
    /**
     * <code>repeated .Book books = 1;</code>
     */
    proto.BookProto.Book getBooks(int index);
    /**
     * <code>repeated .Book books = 1;</code>
     */
    int getBooksCount();
    /**
     * <code>repeated .Book books = 1;</code>
     */
    java.util.List<? extends proto.BookProto.BookOrBuilder> 
        getBooksOrBuilderList();
    /**
     * <code>repeated .Book books = 1;</code>
     */
    proto.BookProto.BookOrBuilder getBooksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BookList}
   */
  public static final class BookList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BookList)
      BookListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "BookList");
    }
    // Use BookList.newBuilder() to construct.
    private BookList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BookList() {
      books_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BookProto.internal_static_BookList_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return proto.BookProto.internal_static_BookList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BookProto.internal_static_BookList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BookProto.BookList.class, proto.BookProto.BookList.Builder.class);
    }

    public static final int BOOKS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<proto.BookProto.Book> books_;
    /**
     * <code>repeated .Book books = 1;</code>
     */
    @java.lang.Override
    public java.util.List<proto.BookProto.Book> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends proto.BookProto.BookOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    @java.lang.Override
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    @java.lang.Override
    public proto.BookProto.Book getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .Book books = 1;</code>
     */
    @java.lang.Override
    public proto.BookProto.BookOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(1, books_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;

          {
            final int count = books_.size();
            for (int i = 0; i < count; i++) {
              size += com.google.protobuf.CodedOutputStream
                .computeMessageSizeNoTag(books_.get(i));
            }
            size += 1 * count;
          }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BookProto.BookList)) {
        return super.equals(obj);
      }
      proto.BookProto.BookList other = (proto.BookProto.BookList) obj;

      if (!getBooksList()
          .equals(other.getBooksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBooksCount() > 0) {
        hash = (37 * hash) + BOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getBooksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BookProto.BookList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.BookList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.BookList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.BookList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.BookList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BookProto.BookList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BookProto.BookList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.BookProto.BookList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.BookProto.BookList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.BookProto.BookList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BookProto.BookList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.BookProto.BookList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BookProto.BookList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookList)
        proto.BookProto.BookListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BookProto.internal_static_BookList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BookProto.internal_static_BookList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BookProto.BookList.class, proto.BookProto.BookList.Builder.class);
      }

      // Construct using proto.BookProto.BookList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
        } else {
          books_ = null;
          booksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BookProto.internal_static_BookList_descriptor;
      }

      @java.lang.Override
      public proto.BookProto.BookList getDefaultInstanceForType() {
        return proto.BookProto.BookList.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BookProto.BookList build() {
        proto.BookProto.BookList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BookProto.BookList buildPartial() {
        proto.BookProto.BookList result = new proto.BookProto.BookList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(proto.BookProto.BookList result) {
        if (booksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            books_ = java.util.Collections.unmodifiableList(books_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.books_ = books_;
        } else {
          result.books_ = booksBuilder_.build();
        }
      }

      private void buildPartial0(proto.BookProto.BookList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BookProto.BookList) {
          return mergeFrom((proto.BookProto.BookList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BookProto.BookList other) {
        if (other == proto.BookProto.BookList.getDefaultInstance()) return this;
        if (booksBuilder_ == null) {
          if (!other.books_.isEmpty()) {
            if (books_.isEmpty()) {
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBooksIsMutable();
              books_.addAll(other.books_);
            }
            onChanged();
          }
        } else {
          if (!other.books_.isEmpty()) {
            if (booksBuilder_.isEmpty()) {
              booksBuilder_.dispose();
              booksBuilder_ = null;
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
              booksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetBooksFieldBuilder() : null;
            } else {
              booksBuilder_.addAllMessages(other.books_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                proto.BookProto.Book m =
                    input.readMessage(
                        proto.BookProto.Book.parser(),
                        extensionRegistry);
                if (booksBuilder_ == null) {
                  ensureBooksIsMutable();
                  books_.add(m);
                } else {
                  booksBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.BookProto.Book> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          books_ = new java.util.ArrayList<proto.BookProto.Book>(books_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.BookProto.Book, proto.BookProto.Book.Builder, proto.BookProto.BookOrBuilder> booksBuilder_;

      /**
       * <code>repeated .Book books = 1;</code>
       */
      public java.util.List<proto.BookProto.Book> getBooksList() {
        if (booksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(books_);
        } else {
          return booksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public int getBooksCount() {
        if (booksBuilder_ == null) {
          return books_.size();
        } else {
          return booksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public proto.BookProto.Book getBooks(int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);
        } else {
          return booksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder setBooks(
          int index, proto.BookProto.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.set(index, value);
          onChanged();
        } else {
          booksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder setBooks(
          int index, proto.BookProto.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.set(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder addBooks(proto.BookProto.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(value);
          onChanged();
        } else {
          booksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder addBooks(
          int index, proto.BookProto.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(index, value);
          onChanged();
        } else {
          booksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder addBooks(
          proto.BookProto.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder addBooks(
          int index, proto.BookProto.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends proto.BookProto.Book> values) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, books_);
          onChanged();
        } else {
          booksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder clearBooks() {
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          booksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public Builder removeBooks(int index) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.remove(index);
          onChanged();
        } else {
          booksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public proto.BookProto.Book.Builder getBooksBuilder(
          int index) {
        return internalGetBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public proto.BookProto.BookOrBuilder getBooksOrBuilder(
          int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);  } else {
          return booksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public java.util.List<? extends proto.BookProto.BookOrBuilder> 
           getBooksOrBuilderList() {
        if (booksBuilder_ != null) {
          return booksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(books_);
        }
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public proto.BookProto.Book.Builder addBooksBuilder() {
        return internalGetBooksFieldBuilder().addBuilder(
            proto.BookProto.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public proto.BookProto.Book.Builder addBooksBuilder(
          int index) {
        return internalGetBooksFieldBuilder().addBuilder(
            index, proto.BookProto.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .Book books = 1;</code>
       */
      public java.util.List<proto.BookProto.Book.Builder> 
           getBooksBuilderList() {
        return internalGetBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.BookProto.Book, proto.BookProto.Book.Builder, proto.BookProto.BookOrBuilder> 
          internalGetBooksFieldBuilder() {
        if (booksBuilder_ == null) {
          booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.BookProto.Book, proto.BookProto.Book.Builder, proto.BookProto.BookOrBuilder>(
                  books_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          books_ = null;
        }
        return booksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BookList)
    }

    // @@protoc_insertion_point(class_scope:BookList)
    private static final proto.BookProto.BookList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BookProto.BookList();
    }

    public static proto.BookProto.BookList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookList>
        PARSER = new com.google.protobuf.AbstractParser<BookList>() {
      @java.lang.Override
      public BookList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BookList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BookProto.BookList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BookList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/book.proto\"@\n\004Book\022\n\n\002id\030\001 \001(\005\022\r" +
      "\n\005title\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022\r\n\005price\030\004" +
      " \001(\005\" \n\010BookList\022\024\n\005books\030\001 \003(\0132\005.BookB\022" +
      "\n\005protoB\tBookProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Book_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Book_descriptor,
        new java.lang.String[] { "Id", "Title", "Author", "Price", });
    internal_static_BookList_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_BookList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BookList_descriptor,
        new java.lang.String[] { "Books", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
